### PR TITLE
Related contraceptives

### PR DESCRIPTION
**Pull request by Esom**

### CODE REVIEW

**Comment by Esom** [comment]
@alexonozor related contraceptice does not update

**Comment by alexonozor** [comment]
Esom please give me the update endpoint you are using  and the payload you
used. Meanwhile,  I tested it and it works well. I will appreciate it if
you always post the errors like a developer and not a user.

Thanks

**Comment by Esom** [comment]
update endpoint: router.put('/contraceptive/:id', ContraceptivesController.updateContraceptive);

do you have any other route to update contraceptives?

**Comment by Esom** [comment]
update endpoint :  router.put('/contraceptive/:id', ContraceptivesController.updateContraceptive);
is there any other update contraceptive route?
resp: 200

**Comment by alexonozor** [comment]
Response is 200 place can I have the payload?

**Comment by alexonozor** [comment]
Okay, please notice all the related product you are updating is working
well when you do /contraceptives I was supposed to have added it to the
response of  /contraceptive/: id which with that you would've seen it.
But we would've figured this out if you have called me or send me what's
app message in realtime, we can't use emails to tackle bugs. Besides, this
is not a bug it just you who didn't check well.

Please check again.

**Pull request merged**
